### ISSUE TITLE
Correct contact form text size on tablet

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#100]
Currently 2.5em
![image](https://cloud.githubusercontent.com/assets/23315246/21508338/682294ba-cc4e-11e6-8434-3aa48ffca190.png)

Should be 28px
![image](https://cloud.githubusercontent.com/assets/23315246/21508353/7f8c470e-cc4e-11e6-833d-b3eade8d0ac9.png)

**Comment by marianovegab** [comment]
Looks good now 


<img width="611" alt="screen shot 2017-01-05 at 1 03 46 pm" src="https://cloud.githubusercontent.com/assets/8145017/21693683/73c2d5fa-d347-11e6-842f-e024cae14c29.png">
