### ISSUE TITLE
Reformat "How we can help you text" to be tablet friendly

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#101]
Currently, it looks like this: 
![image](https://cloud.githubusercontent.com/assets/23315246/21508484/7348d9e8-cc4f-11e6-9426-c3308ddff9b1.png)

Remove line breaks `<br>` to make it look like this:
![image](https://cloud.githubusercontent.com/assets/23315246/21508489/8673e756-cc4f-11e6-8f50-1699aba31853.png)

That will make desktop look too wide, so you can constrain the width to 

@media (min-width: 62em) {
.heresHowWeCanHelpParagraph {
    max-width: 1000px;
    margin-left: calc( ( 100vw - 1000px ) / 2 );
}
}

![image](https://cloud.githubusercontent.com/assets/23315246/21508565/052ec7a0-cc50-11e6-81f8-f74343a0e3b2.png)

**Comment by marianovegab** [comment]
Looking good on tablet and desktop.

<img width="575" alt="screen shot 2017-01-05 at 3 15 44 pm" src="https://cloud.githubusercontent.com/assets/8145017/21697861/0062c238-d35a-11e6-9ec3-5868e1b3f3a8.png">

<img width="1675" alt="screenshot at jan 05 15-16-29" src="https://cloud.githubusercontent.com/assets/8145017/21697860/000eef6e-d35a-11e6-98e7-fdfeb5421c22.png">

Thanks
