### ISSUE TITLE
Adjust Text in Our Process header to be tablet friendly

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#102]
Currently looks like this
![image](https://cloud.githubusercontent.com/assets/23315246/21508675/0355e1c4-cc51-11e6-8420-2e3599ed19fe.png)

Make the text one paragraph (all devices) and change height to 180px (just on tablet) to make it look like this:
![image](https://cloud.githubusercontent.com/assets/23315246/21508728/656e0f26-cc51-11e6-8cb5-287a98b51be5.png)

To fix formatting on desktop add this:

@media (min-width: 62em) {
#ourProcess p {
    max-width: 850px;
    margin-left: calc( ( 100vw - 850px ) / 2 );
}
}

**Comment by marianovegab** [comment]
Height should be 180px for tablet it stil having a space lot of space below "Our Process" paragraph.
<img width="1213" alt="screen shot 2017-01-05 at 3 23 52 pm" src="https://cloud.githubusercontent.com/assets/8145017/21698099/1ec61698-d35b-11e6-8b2f-d8ebb9445791.png">

Thanks

**Comment by luigicr18** [comment]
Height change doesn't change anything.

**Comment by marianovegab** [comment]
@mjbarnes88  Please take a look

**Comment by mjbarnes88** [comment]
For "Our process" section, we should set the max width by px instead of % to ensure that the text breaks at the end of the sentence instead of after the word strict.

This should work.

#ourProcess p {
max-width: 850px;
}

Also, to @marianovegab 's point, there is still too much space below the text.

I would reduce it this way on tablet:

#ourProcess {
    height: 200px;
}

(make sure you use the @media query to constrain the height change to tablet)
