### ISSUE TITLE
Title Tags

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#138]

**Comment by mjbarnes88** [comment]
Home
`<title>Creative Technology - Digital Strategy | SeeSaw Labs</title>'

Work
`<title>Our Work | SeeSaw Labs</title>'

Process
`<title>Our Process | SeeSaw Labs</title>'

Crew
`<title>Our Crew | SeeSaw Labs</title>'

Connect
`<title>Let's Connect | SeeSaw Labs</title>'

**Comment by jkalderonkiros** [comment]
done

**Comment by mjbarnes88** [comment]
Could you capitalize the second word in each title tag? 

Example: Our work vs. Our Work

@jkalderonkiros

**Comment by jkalderonkiros** [comment]
@luigicr18 please take care of this
