### ISSUE TITLE
Let's connect page

### ISSUE THREAD

**Issue by jkalderonkiros** [seesawlabs/seesawlabs.github.io#145]

**Comment by jkalderonkiros** [comment]
@luigicr18 
Please all message to let know the user when the message was send successfully
Please check the validation styles in firefox

**Comment by mjbarnes88** [comment]
Text size for entries should match the text they replace (currently too small)
![image](https://cloud.githubusercontent.com/assets/23315246/22422402/26456212-e6ba-11e6-94bc-b9ab1f1895c7.png)

**Comment by mjbarnes88** [comment]
Confirmation message is currently, "Message was send successfully"
(send should be "sent")

Let's just change to, "Your message was sent successfully! We'll get back to you shortly."

**Comment by mjbarnes88** [comment]
While you're in there, could you also change the line thickness of the boarders for the fields to 1px instead of 2px @luigicr18 ?

**Comment by mjbarnes88** [comment]
Looks much better @luigicr18 

Could we also center the confirmation message?

**Comment by luigicr18** [comment]
@mjbarnes88 Could you give me an example of what you want? Because right now the message is center and in the middle of the content.

**Comment by mjbarnes88** [comment]
Center the text horizontally (is already centered vertically)

![image](https://cloud.githubusercontent.com/assets/23315246/22567295/603adb1e-e95d-11e6-8efe-faba93de4312.png)
