### ISSUE TITLE
Our Crew - text edit

### ISSUE THREAD

**Issue by JoconOfWan** [seesawlabs/seesawlabs.github.io#152]
"One of the advantages of partnering with SeeSaw Labs is immediate, cost-effective access to our many years of experience **across myriad diciplines.**"

should be:
**across a myriad of disciplines**

**Comment by mjbarnes88** [comment]
@luigicr18  is this one ready? not seeing it.

**Comment by luigicr18** [comment]
@mjbarnes88 test it again.

**Comment by mjbarnes88** [comment]
sweet. thanks!
