### ISSUE TITLE
Our Crew - text leading issue

### ISSUE THREAD

**Issue by JoconOfWan** [seesawlabs/seesawlabs.github.io#153]
Text leading on From the Lab section is non-exisitent, ie the space between text lines is not there as it is in other sections on page.

![image](https://cloud.githubusercontent.com/assets/25378711/22495628/f2f1a836-e807-11e6-9b4c-eec5e89289ea.png)

**Comment by mjbarnes88** [comment]
@luigicr18 increase line-height from 17px to 21px as in the other sections.
