### ISSUE TITLE
Digital Execution Text on Mobile too long

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#158]
@jefftulsa 's text edit was a bit long and now intersects with the Go Backstage button on mobile

Options:

1. Cut the text down a bit
2. Add Some space there. I may need to make the background larger in this case.

My personal opinion is that the text is perhaps a bit too long to be expected to be read in it's entirety. 
(and looks a bit awkward next to the shorter text in Exploration)

Perhaps the first paragraph is more appropriate in the hero?

![image](https://cloud.githubusercontent.com/assets/23315246/22567773/48381656-e95f-11e6-8b43-881a8493ddc8.png)

**Comment by jefftulsa** [comment]
Please change the copy to the following:

```
We get start-ups started. We bring life to creative agencies' visions. We modernize legacy systems. We maintain everything we build.

Full life cycle, cross-platform custom software product development.
```
