### ISSUE TITLE
Looks like Home Page got messed up

### ISSUE THREAD

**Issue by JoconOfWan** [seesawlabs/seesawlabs.github.io#170]
![image](https://cloud.githubusercontent.com/assets/25378711/22679720/d123b782-ecc9-11e6-93fa-b512ad7d013f.png)

text from tech strategy banner is bleeding into the case study. Did someone QA this? sorry if you've already documented, but I didn't see it.

**Comment by mjbarnes88** [comment]
@luigicr18 Section too short on Desktop, iPad Pro and mobile sized resolution on Desktop
![image](https://cloud.githubusercontent.com/assets/23315246/22692673/06a7dc32-ed0e-11e6-9fdc-6b6e06ab257a.png)


Everything looks fine on Mobile when viewed from an iPhone or traditional iPad.

**Comment by mjbarnes88** [comment]
Creative in Other Services misaligned on hover (For screen sizes larger than 1440px wide)

![image](https://cloud.githubusercontent.com/assets/23315246/22696130/01e60f36-ed1b-11e6-8daa-5c64e4c4077a.png)

![image](https://cloud.githubusercontent.com/assets/23315246/22696151/0e027890-ed1b-11e6-8e92-35d6d7b1f864.png)


When you hover over, the image shifts

Also, please check the experience on small resolution for desktop again.
