### ISSUE TITLE
Update Our Crew VR

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#176]
Screenshot Desktop:
![image](https://cloud.githubusercontent.com/assets/23315246/23313977/de63035e-fa8d-11e6-86c8-911b68453cef.png)

Screenshot Mobile:
![image](https://cloud.githubusercontent.com/assets/23315246/23314308/6e1b88da-fa8f-11e6-8e23-062098122f62.png)

Assets:
This shares the same assets as the homepage found in the shared folder under Homepage > Assets

Backgrounds:
Only change is to mobile background. You'll find it in shared folder under Backgrounds > Crew 

Links:
Google Play Store:
https://play.google.com/store/apps/details?id=com.seesawlabs.rockstar

Apple App Store: TBD

Play in Browser: TBD

**Comment by luigicr18** [comment]
Pending links
