### ISSUE TITLE
SSL not working on new site

### ISSUE THREAD

**Issue by jefftulsa** [seesawlabs/seesawlabs.github.io#2]
When I simply type "seesawlabs.com" into a browser, Google attempts to pull it up as https://seesawlabs.com. We have a valid cert, but I am sure it has not been setup in our newly hosted environment.

The movement for ssl everywhere is afoot, so we need to address this issue:

![seesaw-ssl-issue](https://cloud.githubusercontent.com/assets/299167/7285608/59740f5c-e90b-11e4-852e-313dd04700da.png)

**Comment by ivanmorales** [comment]
This one might be more along your expertise:
https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it

**Comment by cs45977** [comment]
@jefftulsa @ivanmorales 
Apparently Github now requires SSH for new github pages , but will not support ssl on custom domains.
I'd suggest we move off github pages 
#eatyourowndogfood
