### ISSUE TITLE
New Navigation

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#49]
Notes here:
![image](https://cloud.githubusercontent.com/assets/23315246/20887137/702675b6-bac7-11e6-941b-f84f964fc1da.png)

Relevant files in Google Drive

**Comment by mjbarnes88** [comment]
Navigation Bar is persistent
Background is black and has opacity of 75%

**Comment by luigicr18** [comment]
Need to know if the font-size change on the menu, and also if the "hover" color of the links change?

**Comment by mjbarnes88** [comment]
15px bold

#6bbad9 on hover @luigicr18

**Comment by marianovegab** [comment]
Hello @mjbarnes88 @luigicr18 

Please take a look at this screenshot 
<img width="1198" alt="screenshot at dec 12 15-33-50" src="https://cloud.githubusercontent.com/assets/8145017/21117847/04b20e3e-c081-11e6-9a52-27ee16b3de14.png">

Thanks

**Comment by mjbarnes88** [comment]
@luigicr18 also ensure that the logo is 100% opacity while the background is only 75% Can't quite tell from photo but it looks like logo might also be semi-transparent

**Comment by marianovegab** [comment]
Hello
This is looking good now.
<img width="424" alt="screen shot 2016-12-15 at 11 59 16 am" src="https://cloud.githubusercontent.com/assets/8145017/21235798/ee8ccf10-c2bd-11e6-8ee1-ff7226fdbe0f.png">
Thanks

**Comment by mjbarnes88** [comment]
![image](https://cloud.githubusercontent.com/assets/23315246/21242749/c3ef1c60-c2e3-11e6-9aa0-cb3d35fd84f5.png)

Both nav bar and logo at currently at 75% opacity. 
The logo should be at 100%

.mobileNav, .navbar {
    background-color: #000;
    opacity: .75;
}

Instead do this:

.mobileNav, .navbar {
    background-color: rgba(0, 0, 0, 0.75);}
    opacity: 1;
}

**Comment by mjbarnes88** [comment]
Vertically center nav elements: 
![image](https://cloud.githubusercontent.com/assets/23315246/21242788/f756b874-c2e3-11e6-921e-3182d0712822.png)

Also increase space between to match mock (see above)

**Comment by mjbarnes88** [comment]
Spacing fixed. Please also ensure that when a navigation link it clicked to takes you to the correct section without the heading text covered by the navigation bar.

![image](https://cloud.githubusercontent.com/assets/23315246/21297403/e44b0b48-c54c-11e6-9b59-eac0f3931db7.png)

Like this
![image](https://cloud.githubusercontent.com/assets/23315246/21297407/31d59c34-c54d-11e6-8adc-58713d5ce93d.png)

Also it looks like the corners of the nav bar are rounded. Remove this.
![image](https://cloud.githubusercontent.com/assets/23315246/21297414/6eabcafc-c54d-11e6-96cf-87e909d74c14.png)


Could you also make this be a scroll transition when clicked, instead of instead of jumping instantly?
(if you'd rather this be a separate ticket let me know)

**Comment by mjbarnes88** [comment]
Corners look good. Added Scrolling issue as a new ticket.
