### ISSUE TITLE
fix the about section

### ISSUE THREAD

**Issue by jefftulsa** [seesawlabs/seesawlabs.github.io#5]
A couple things in the about section need adjustments:

1) Since we have the map there, let's start off the section with
"SeeSaw Labs is a software design and build shop located in Austin, TX. We create cross-platform products that grow your business."

2) Then we can do into the marketing copy, which currently on the live site has a duplicate sentence on the end of the first blub:
The seesaw is a simple machine: a device that uses mechanical advantage to multiply force and an elementary building block from which more complex machines are built._: a device that uses mechanical advantage to multiply force._ 

remove that last line

**Comment by ivanmorales** [comment]
I'm not exactly sure what you need.  I updated what I think you were saying. 

This is the file you need to update to make changes:
https://github.com/seesawlabs/seesawlabs.github.io/blob/master/_includes/about.html#L16
