### ISSUE TITLE
Hero Image

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#50]
Notes:
![image](https://cloud.githubusercontent.com/assets/23315246/20887375/4c20d55c-bac8-11e6-802d-64d7295ee64f.png)

Everything you need:
https://drive.google.com/drive/folders/0B5DWXoUiIyAJbU5yR0gzMlliQlk?usp=sharing

**Comment by marianovegab** [comment]
QA in progress

**Comment by marianovegab** [comment]
Hello guys @mjbarnes88  @luigicr18 

On 3360px width the "explore our services"  button appear to large, it shouldn't have a max width for big screens ?

Please take a look.
<img width="1677" alt="screenshot at dec 12 15-18-59" src="https://cloud.githubusercontent.com/assets/8145017/21117211/59ac7e86-c07e-11e6-9a31-25f3926fbf0a.png">

Thanks

**Comment by marianovegab** [comment]
Hello
Button is looking good now
<img width="854" alt="screen shot 2016-12-15 at 11 53 38 am" src="https://cloud.githubusercontent.com/assets/8145017/21235628/2bb60146-c2bd-11e6-8fd9-c21c3ffb223b.png">

**Comment by mjbarnes88** [comment]
Font family incorrect. 

should be:

#homepageHeroText h1 {
    font-family: openSansExtraBold;
}

for button hover lets go with:

button#exploreCaseStudiesButton:hover {
    background-color: #226a85;
}

**Comment by mjbarnes88** [comment]
@luigicr18 Looks good. Just make sure to confine the text and button to a max width as noted in #66
