### ISSUE TITLE
New Navigation - MOBILE

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#52]
Notes:
![image](https://cloud.githubusercontent.com/assets/23315246/20888339/72fa91f0-bacc-11e6-8c0a-11efcf8885ae.png)

**Comment by luigicr18** [comment]
Need font-size and margins for text on the "hero" section.

**Comment by mjbarnes88** [comment]
@luigicr18 see #54 I've only included font size notes when they differ from the desktop version.

When in doubt, you can also compare to the style guide in the shared folder

**Comment by marianovegab** [comment]
Hello @mjbarnes88 @luigicr18 
Please take a look at this notes

1- Menu button is not working.
![whatsapp image 2016-12-15 at 10 46 56 am](https://cloud.githubusercontent.com/assets/8145017/21233180/d84e0d68-c2b3-11e6-9f1a-6d7679e5b850.jpeg)

2-Please take a look at the menu it looks different
<img width="674" alt="screenshot at dec 15 11-02-00" src="https://cloud.githubusercontent.com/assets/8145017/21233769/08236fa4-c2b6-11e6-8035-18841d4ff100.png">

Thanks

**Comment by luigicr18** [comment]
This is an element from fontawesome, we can't modify the lines just the size.

**Comment by marianovegab** [comment]
Hello
@mjbarnes88 do you think is ok if @luigicr18 use an image instead of the fontawesome.

Thanks

**Comment by mjbarnes88** [comment]
@marianovegab Yes, @luigicr18 I'll add an svg icon for this into the drive folder. The FA one doesn't really fit the aesthetic.

**Comment by mjbarnes88** [comment]
https://drive.google.com/open?id=0B5DWXoUiIyAJUTFPTHc0c2hGVTQ

**Comment by mjbarnes88** [comment]
Icon looks good.
