### ISSUE TITLE
How we can help section (1h)

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#53]
Notes:
![image](https://cloud.githubusercontent.com/assets/23315246/20928851/a1deb68a-bb95-11e6-999c-3744da0b8d74.png)

**Comment by marianovegab** [comment]
QA in progress

**Comment by marianovegab** [comment]
Hello @luigicr18  @mjbarnes88 

Everything is looking good here just take a look at this notes.

Note:
The width of the <p> is not the expected.
<img width="496" alt="screenshot at dec 12 18-13-48" src="https://cloud.githubusercontent.com/assets/8145017/21122262/b788d4f6-c096-11e6-9566-09ce65c29728.png">

Thanks

**Comment by marianovegab** [comment]
Hello
This is looking good.
<img width="1614" alt="screen shot 2016-12-15 at 1 20 46 pm" src="https://cloud.githubusercontent.com/assets/8145017/21238635/62738404-c2c9-11e6-9e5e-a80b2c20a462.png">
Thanks

**Comment by mjbarnes88** [comment]
Once #66 is addressed, the width will be fixed, but for the type. Roboto Light is specified.

Replace with this:

#homepageServiceBoxContainer p {
    font-family: **roboto**;
    **font-weight: 300;**
}

**Comment by mjbarnes88** [comment]
font now correct. Thanks!
