### ISSUE TITLE
Hero - MOBILE(1.5h)

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#54]
Notes:
![image](https://cloud.githubusercontent.com/assets/23315246/20929252/5256e4d2-bb97-11e6-8373-db58f208ec27.png)

With regard to font size, everything else is the same if not noted otherwise.

**Comment by marianovegab** [comment]
Hello
This is looking good.

<img width="548" alt="screenshot at dec 15 10-58-03" src="https://cloud.githubusercontent.com/assets/8145017/21234158/4d49c42e-c2b7-11e6-8aa6-5d1b3c350e03.png">

Thanks

**Comment by mjbarnes88** [comment]
Move Hambuger over as @marianovegab  mentioned.

Font size 15px is being overwritten
![image](https://cloud.githubusercontent.com/assets/23315246/21264981/29a83670-c36d-11e6-92ea-d4dbe30a5523.png)

Increase padding above and below button to match mock

**Comment by mjbarnes88** [comment]
Font is now correct, but you need to increase padding at the top and around button to match the mockup
![image](https://cloud.githubusercontent.com/assets/23315246/21297721/b22f2df0-c552-11e6-9b1a-f15cf092593a.png)

#homepageHeroText {
    margin: 8em 0.5em 0;
}

#homepageHeroText h1 {
    margin-bottom: 0.75em;
}

#exploreCaseStudies {
    margin: 1em 0 2em 0;
}

Result will look like this
![image](https://cloud.githubusercontent.com/assets/23315246/21297727/d2192594-c552-11e6-8e9b-bea4bdd8a74a.png)

**Comment by mjbarnes88** [comment]
@media (max-width: 24.375em)
#homepageHeroText p {
    font-size: 18px;
}

I realized from the mock that the 15px specified is for the margin (which you have) not the text size. 
Paragraph text can remain 18px. Sorry for the confusion.

**Comment by mjbarnes88** [comment]
Text looks good but the button is offset now?

button#exploreCaseStudiesButton {
    width: 300px;
    height: 50px;
    margin-left: calc( ( 100vw - 300px ) / 2 );
}
