### ISSUE TITLE
Case Studies Section - MOBILE (0.5 h)

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#55]
Notes:
![image](https://cloud.githubusercontent.com/assets/23315246/20929419/04c4f028-bb98-11e6-85b8-dd8d58ad4a4c.png)

**Comment by marianovegab** [comment]
Hello @luigicr18 @mjbarnes88 

1- Please take look at the "Client Case Studies" text it is not in the centered .
<img width="413" alt="screenshot at dec 15 11-27-34" src="https://cloud.githubusercontent.com/assets/8145017/21234799/c6ad82d6-c2b9-11e6-8506-9624208826b1.png">

2- Learn more link is not appearing.
<img width="412" alt="screenshot at dec 15 11-30-27" src="https://cloud.githubusercontent.com/assets/8145017/21234883/1e745d32-c2ba-11e6-95c1-ee04e27fbea9.png">
<img width="411" alt="screenshot at dec 15 11-32-32" src="https://cloud.githubusercontent.com/assets/8145017/21234901/3099a210-c2ba-11e6-8bc9-8a7f8b1fc1a3.png">

3-There is a white line between two Client Cases
<img width="410" alt="screenshot at dec 15 11-47-10" src="https://cloud.githubusercontent.com/assets/8145017/21235471/7e514f06-c2bc-11e6-9dc3-550e5e6999f2.png">

Thanks

**Comment by luigicr18** [comment]
For mobile "Learn more" link shouldn't display.

**Comment by mjbarnes88** [comment]
Looks great! @luigicr18
