### ISSUE TITLE
How We Can Help Section - MOBILE(0.5h)

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#56]
notes: 
![image](https://cloud.githubusercontent.com/assets/23315246/20929540/77f451ce-bb98-11e6-89ae-c9591e3df87e.png)

Almost everything else is the same in the mobile version (just vertically aligned of course

**Comment by marianovegab** [comment]
Hello @luigicr18 
Please take a look at this notes:
1-There is to much space between <p> and tittle.
<img width="399" alt="screenshot at dec 15 13-59-10" src="https://cloud.githubusercontent.com/assets/8145017/21239987/ed46cce4-c2ce-11e6-9d29-79651c25dfd4.png">
Thanks

**Comment by mjbarnes88** [comment]
Fix spacing per @marianovegab 's comment and we're good here.

**Comment by mjbarnes88** [comment]
Thanks.
