### ISSUE TITLE
Our Process Section(2h)

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#57]
Notes: 
![image](https://cloud.githubusercontent.com/assets/23315246/20936596/28736f7c-bbb1-11e6-9a92-63787fa952d3.png)

**Comment by marianovegab** [comment]
Hello Guys @luigicr18 @mjbarnes88 
Please take a look at this notes.
Notes:
1- There is no space between first and second line of text.
2- Font is regular and it should be light.
<img width="1650" alt="screenshot at dec 12 18-57-00" src="https://cloud.githubusercontent.com/assets/8145017/21124166/d6732fae-c0a2-11e6-9efe-f16e740dd036.png">

3- The color of the tittlo is not of the same color than in comps and it should be on capital letters
<img width="1529" alt="screenshot at dec 12 19-46-53" src="https://cloud.githubusercontent.com/assets/8145017/21124472/cd1785a2-c0a4-11e6-9fbd-deb653e08559.png">

Thanks

**Comment by marianovegab** [comment]
Hello 
This is looking good.
<img width="1140" alt="screen shot 2016-12-15 at 1 39 50 pm" src="https://cloud.githubusercontent.com/assets/8145017/21239313/feb7b5cc-c2cb-11e6-8b37-71c02dc7de2a.png">

Thanks

**Comment by mjbarnes88** [comment]
![image](https://cloud.githubusercontent.com/assets/23315246/21263715/5100b42e-c366-11e6-9eac-3e20006cfca2.png)

Alignment of sections is off. Since the image will always be the same height on desktop (or you can force it to be), use a relative positioning in the parent and absolute positioning for the children. Like this:

![image](https://cloud.githubusercontent.com/assets/23315246/21264318/bc83bdce-c369-11e6-98db-a6f0bca08d1a.png)

Also please make text Roboto Light

.section2DesktopColRight p {
    font-size: 16px;
    font-family: roboto;
    font-weight: 300;
}

**Comment by mjbarnes88** [comment]
Font is correct, but alignment is still incorrect. Please relook at this screenshot. I have provided the exact CSS you need to get this correct. I'll also include my comment again:

"Alignment of sections is off. Since the image will always be the same height on desktop (or you can force it to be), use a relative positioning in the parent and absolute positioning for the children. Like this:"

![image](https://cloud.githubusercontent.com/assets/23315246/21297617/207a381a-c551-11e6-81e2-f70672cb4ffb.png)

**Comment by mjbarnes88** [comment]
Looks great!
