### ISSUE TITLE
Our Process Section - MOBILE(3h)

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#58]
Notes:
![image](https://cloud.githubusercontent.com/assets/23315246/20936890/62464250-bbb2-11e6-93cf-9971e909f409.png)

**Comment by marianovegab** [comment]
Hello 
Please take a look at this notes:
1- <img width="643" alt="screenshot at dec 15 14-59-28" src="https://cloud.githubusercontent.com/assets/8145017/21241832/2c877586-c2d7-11e6-85bd-4158a69d267c.png">
Thanks

**Comment by mjbarnes88** [comment]
@luigicr18 This CSS is fine for 2 Line text, but fails for one line and the first case (with no arrow at the top).
The text should be centered on the beaker.

.h2DivHeader {
    display: inline-block;
    width: 70%;
    padding: 5em 0 0 2.5em;
}

![image](https://cloud.githubusercontent.com/assets/23315246/21297192/58cc2a50-c549-11e6-8571-051fe999c30c.png)

Use 3em instead of 5 for the first one (also add the padding per @marianovegab 's request)
![image](https://cloud.githubusercontent.com/assets/23315246/21297205/c41935e6-c549-11e6-86c7-457d85ea0399.png)

use 5.75em for the spacing of 1 Line titles (that aren't the first one)
![image](https://cloud.githubusercontent.com/assets/23315246/21297349/020b8d66-c54c-11e6-933e-2a93b33d4b48.png)

**Comment by mjbarnes88** [comment]
I see that you tried to use position absolute and top 25% but this doesn't work. The alignment is still off.

While it isn't as clean as it could be to use different values for the different sections, please just use the suggestion I provided so that the alignment looks correct.

Examples of incorrect currently:
![image](https://cloud.githubusercontent.com/assets/23315246/21353710/3ad230ce-c695-11e6-9f3a-594fa5d020f0.png)
![image](https://cloud.githubusercontent.com/assets/23315246/21353745/5c0b868c-c695-11e6-882f-4d80cdb666ca.png)

**Comment by mjbarnes88** [comment]
Looks good now
