### ISSUE TITLE
Leadership Section(2h)

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#59]
Notes: 
![image](https://cloud.githubusercontent.com/assets/23315246/20956971/1ae4edb2-bc1b-11e6-9b09-ee6d04ca234a.png)

**Comment by marianovegab** [comment]
Hello @luigicr18 @mjbarnes88 
Please take a look at these notes
1- Just the first letter of the names should be capital letter
<img width="783" alt="screenshot at dec 12 20-26-11" src="https://cloud.githubusercontent.com/assets/8145017/21125262/dbdc6e04-c0a9-11e6-80ca-59d3bbae744a.png">

2-Width of < p > should be 350px width.
<img width="739" alt="screenshot at dec 12 20-21-10" src="https://cloud.githubusercontent.com/assets/8145017/21125263/dbee707c-c0a9-11e6-8336-b44f67e51b94.png">

3- Body should be 1180px width 
<img width="1542" alt="screenshot at dec 12 20-28-29" src="https://cloud.githubusercontent.com/assets/8145017/21125265/dbfa3f42-c0a9-11e6-9c3f-39de05ad30dd.png">

4- Text on image should be light font
<img width="1236" alt="screenshot at dec 12 20-13-46" src="https://cloud.githubusercontent.com/assets/8145017/21125268/dbfe7ae4-c0a9-11e6-8a75-8d2045ed1d99.png">

5- < p > should be 16px light roboto 
<img width="1459" alt="screenshot at dec 12 20-20-05" src="https://cloud.githubusercontent.com/assets/8145017/21125266/dbfac692-c0a9-11e6-9a31-b3f9efcc98cc.png">

6- 
<img width="1364" alt="screenshot at dec 12 20-17-06" src="https://cloud.githubusercontent.com/assets/8145017/21125264/dbfa3b0a-c0a9-11e6-9faf-7e519be5eaf6.png">
<img width="1251" alt="screenshot at dec 12 20-23-17" src="https://cloud.githubusercontent.com/assets/8145017/21125267/dbfcd69e-c0a9-11e6-993c-a05a636f9e79.png">


Thanks

**Comment by marianovegab** [comment]
Hello 
This is now looking good
Thanks

**Comment by mjbarnes88** [comment]
font family used in bio doesn't exist "robotoLight"

instead use

.styleGuideP {
    font-family: roboto;
    font-weight: 300;
}

**Comment by mjbarnes88** [comment]
Spacing will be fixed per #66 but font is now correct.
