### ISSUE TITLE
Contact Section

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#60]
Notes:
![image](https://cloud.githubusercontent.com/assets/23315246/20956816/49b79ad2-bc1a-11e6-84ed-89862704de99.png)

**Comment by marianovegab** [comment]
Hello Guys @luigicr18 @mjbarnes88 
Please take a look at this notes

<img width="1452" alt="screenshot at dec 13 04-03-51" src="https://cloud.githubusercontent.com/assets/8145017/21135967/3da8ee52-c0e9-11e6-9677-9fe6a69afd37.png">
<img width="1197" alt="screenshot at dec 13 04-02-02" src="https://cloud.githubusercontent.com/assets/8145017/21135965/3da84d80-c0e9-11e6-86d3-bea99b5af699.png">
<img width="1436" alt="screenshot at dec 13 03-33-49" src="https://cloud.githubusercontent.com/assets/8145017/21135966/3da84a92-c0e9-11e6-9220-77f4008ec202.png">
<img width="1344" alt="screenshot at dec 13 03-37-17" src="https://cloud.githubusercontent.com/assets/8145017/21135969/3da9f982-c0e9-11e6-8e17-ec41a83f07bc.png">
<img width="1570" alt="screenshot at dec 13 03-39-07" src="https://cloud.githubusercontent.com/assets/8145017/21135968/3da93cea-c0e9-11e6-93d2-29a585d22013.png">

Thanks

**Comment by marianovegab** [comment]
Hello 
Please take a look at this overlaps

<img width="1679" alt="screenshot at dec 15 14-13-19" src="https://cloud.githubusercontent.com/assets/8145017/21240399/bf90c398-c2d0-11e6-9ffd-6974c4762b18.png">

Thanks

**Comment by mjbarnes88** [comment]
![image](https://cloud.githubusercontent.com/assets/23315246/21297082/13910a2a-c547-11e6-8912-4eb754dcedf6.png)

**Comment by mjbarnes88** [comment]
@luigicr18 Actually it's not the text that is improperly centered, its the form.
You've centered the form in the remaining space to the left of the bubbles. The bubbles should be part of the background.
![image](https://cloud.githubusercontent.com/assets/23315246/21297152/6662f8d4-c548-11e6-85a0-b800b3059a5a.png)

**Comment by mjbarnes88** [comment]
Padding between form sections is still incorrect. Use this:

.textAlignRight {
    text-align: right;
    margin: 5px 0;
    padding-right: 5px;
}

.textAlignLeft {
    text-align: left;
    margin: 5px 0;
    padding-left: 5px;
}

.textAreaDiv {
    width: 100%;
    display: block;
    padding-bottom: 1em;
    padding-top: 5px;
}

.form-group textarea {
    width: 730px;
    display: block;
    margin: auto;
    border-radius: 0;
}

Button needs to look like mock. Use this:

@media (min-width: 34em)
.contactFormButtonDiv button {
    width: 250px;
    height: 50px;
}

**Comment by mjbarnes88** [comment]
You still need to make this change:

.form-group textarea {
    width: 730px;
}
