### ISSUE TITLE
Leadership Team - MOBILE

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#61]
notes: 
![image](https://cloud.githubusercontent.com/assets/23315246/20957038/78ae16f8-bc1b-11e6-9a51-8f9342aa7331.png)

**Comment by mjbarnes88** [comment]
To accommodate space, name and title font are different from desktop and for me, my title is in 13px instead of 16px

![image](https://cloud.githubusercontent.com/assets/23315246/20957123/dc993cba-bc1b-11e6-9e30-86242467088c.png)

**Comment by marianovegab** [comment]
Hello 
Please take a look at this < p > the font is not the expected
<img width="487" alt="screenshot at dec 15 15-27-33" src="https://cloud.githubusercontent.com/assets/8145017/21242679/10dca3b6-c2db-11e6-88b6-77a8932a0816.png">
Thanks

**Comment by marianovegab** [comment]
Hello @luigicr18 
Just to confirm the right font should be 
font-family: roboto
font-weight: 300
Thanks

**Comment by mjbarnes88** [comment]
Font now correct.
