### ISSUE TITLE
Contact Section - MOBILE

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#62]
Notes:
![image](https://cloud.githubusercontent.com/assets/23315246/20957185/3dc3f44e-bc1c-11e6-996f-4a55e2afc976.png)

**Comment by luigicr18** [comment]
The width of 350px can't be use for all mobile versions, because we have small mobile widths than 350px, so I used a percentage to adjust the textboxes and a margin on both sides.

**Comment by marianovegab** [comment]
Hello @mjbarnes88  @luigicr18 
Please take a look at this notes.

<img width="541" alt="screenshot at dec 16 09-08-36" src="https://cloud.githubusercontent.com/assets/8145017/21267268/41f5ed2e-c36f-11e6-8a38-7b3da0a669d7.png">

Thanks

**Comment by mjbarnes88** [comment]
Once Button text size and case is correct, please center it vertically. Also please center the field text within their respective boxes. See mock at beginning of this ticket.

![image](https://cloud.githubusercontent.com/assets/23315246/21297808/ae7b2bc6-c554-11e6-8da4-e621eb2fdeb8.png)

**Comment by mjbarnes88** [comment]
Please make the button text match the button text in the hero section. 
Currently they are different font families, size and weight...

![image](https://cloud.githubusercontent.com/assets/23315246/21353007/0bff0f72-c692-11e6-9713-0cf98303902a.png)

![image](https://cloud.githubusercontent.com/assets/23315246/21353030/2640729a-c692-11e6-940c-f1cb381e8ed4.png)

**Comment by mjbarnes88** [comment]
Please make this text match the mockup
![image](https://cloud.githubusercontent.com/assets/23315246/21353085/6fb56d7c-c692-11e6-8439-3d939eb6c725.png)

The font-size should remain 28px. 
Add margin: 20px 15px;

![image](https://cloud.githubusercontent.com/assets/23315246/21353256/3345955a-c693-11e6-8015-cb211374710d.png)

**Comment by mjbarnes88** [comment]
Great.
