### ISSUE TITLE
Case Studies Section Expanded

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#63]
Notes:
On click of each of the two case study tiles, insert inline the section below.

Use copy in google doc, probably some typos in mockup
https://docs.google.com/a/seesawlabs.com/document/d/1xj8305IoNdJDJvozXd1TJaptf1VL9bWWjj4erbgAyPs/edit?usp=sharing

Mockup
![casestudies-80](https://cloud.githubusercontent.com/assets/23315246/21022010/0ebd921c-bd49-11e6-83a7-abe48a034af5.jpg)
![asset 33-80](https://cloud.githubusercontent.com/assets/23315246/21023073/f4765a02-bd4c-11e6-8647-322167d3477e.jpg)
![asset 34-80](https://cloud.githubusercontent.com/assets/23315246/21023072/f4714bca-bd4c-11e6-995a-f35a18e07b7c.jpg)

Marked up
![image](https://cloud.githubusercontent.com/assets/23315246/21023113/25a3ff12-bd4d-11e6-8a37-c22b8b052772.png)

Additional notes: 
I'm including the assets for the tiles in the drive folder

By default, the case study tiles have a 75% opacity black filter over top of them. The logo, line of text, and "learn more" sits on top.
When active, that opacity drops to 50% and the other, inactive tile gets an additional 75% filter applied over top of the entire tile (logo, text and learn more included).

I had also considered overlaying this new section over "other happy clients" when hovered over, this would need to be an on-touch option for tablet, however I wanted to ensure that there is enough room for the text, so I went with the the inline insertion. We can keep this idea on the table if there is some other complication.

**Comment by marianovegab** [comment]
Hello
Please take a look at this notes:
1-Images appear duplicated
<img width="1679" alt="screenshot at dec 15 14-21-15" src="https://cloud.githubusercontent.com/assets/8145017/21240656/d8427eda-c2d1-11e6-96e3-9028ccff4a8e.png">

2- Border of images have a white line:
<img width="959" alt="screenshot at dec 15 14-26-12" src="https://cloud.githubusercontent.com/assets/8145017/21240800/76d41b44-c2d2-11e6-9ce4-8095ad687a5b.png">

Thanks

**Comment by mjbarnes88** [comment]
@luigicr18 As we discussed, please use a rgba value filter over a single image instead of using two separate images for the hover effect.

**Comment by mjbarnes88** [comment]
Using one image now, thanks!
