### ISSUE TITLE
Case Study Section Expanded - MOBILE

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#64]
Notes:
![image](https://cloud.githubusercontent.com/assets/23315246/21023705/b482f484-bd4f-11e6-899c-bd3078beb93a.png)

Marked up:
![image](https://cloud.githubusercontent.com/assets/23315246/21023806/16134a78-bd50-11e6-9438-d480b1bf8c73.png)

**Comment by mjbarnes88** [comment]
@marianovegab for this section, we're gong to have @luigicr18 have the sections fully expanded. Later if we decide that we need a collapse/expand function we can create a new ticket.

**Comment by mjbarnes88** [comment]
Additionally, we'll exclude the second photo on mobile

**Comment by marianovegab** [comment]
This is looking good.

**Comment by mjbarnes88** [comment]
@luigicr18 I'm going to update the images in the google drive folder (to fix the 1px white line) I'll DM you when that is done in just a bit. 

Please put the 50% opacity black filter over the images but under the text (as is done in desktop version)

**Comment by mjbarnes88** [comment]
Looks good. Making a note here that for length purposes we have decided to hide the "other happy clients" section but could reverse this decision if needed.
