### ISSUE TITLE
Send a message is not sending messages

### ISSUE THREAD

**Issue by marianovegab** [seesawlabs/seesawlabs.github.io#88]
## Links for test
https://luigicr18.github.io/seesawlabs.github.io/

## Steps to Reproduce / Test
1- Go to https://luigicr18.github.io/seesawlabs.github.io/ on iPhone 6s 
2- Scroll down to "Let's chat about how we can partner together."
3- fill the form and click on "Send a message" button

**Expected Result**
It should show a successful message

**Actual Result**
Instead it is deleting the information "Your Name", "Your email" and "Your message" spaces

## Annotated Wireframes / Screenshots
<img width="866" alt="screen shot 2016-12-23 at 4 17 47 pm" src="https://cloud.githubusercontent.com/assets/8145017/21463225/8fcd5f84-c92b-11e6-824e-9f7b99c44ac2.png">
<img width="1233" alt="screen shot 2016-12-23 at 4 13 25 pm" src="https://cloud.githubusercontent.com/assets/8145017/21463226/92704ef4-c92b-11e6-8f8d-56e1ee50c73a.png">

NOTE:
This is happening on live please take a look

**Comment by mjbarnes88** [comment]
Yes, @luigicr18 Let's show a confirmation message after submission:

Like this:
![image](https://cloud.githubusercontent.com/assets/23315246/21507309/442b39e4-cc45-11e6-977f-276a2a51597c.png)


Same font as the title above

**Comment by marianovegab** [comment]
Hello
This is working good now.

<img width="1677" alt="screenshot at jan 05 12-41-12" src="https://cloud.githubusercontent.com/assets/8145017/21692841/422262ca-d344-11e6-812e-9577caa6a760.png">

Thanks

**Comment by mjbarnes88** [comment]
Please make sure that the size of the container doesn't change after submission
![image](https://cloud.githubusercontent.com/assets/23315246/21724474/8415041c-d402-11e6-9f44-dc019e7adcdf.png)
![image](https://cloud.githubusercontent.com/assets/23315246/21724490/9304a4fa-d402-11e6-8daf-deef663b8fa1.png)

Also, please make sure to center the "Message Sent" text is centered between the text above and the bottom of the container as is shown in the mockup. Let me know if that doesn't make sense @luigicr18

**Comment by marianovegab** [comment]
This is looking good the size is not changing 

<img width="1610" alt="screen shot 2017-01-06 at 3 04 19 pm" src="https://cloud.githubusercontent.com/assets/8145017/21732897/726b2682-d421-11e6-9207-96c977ecbe5c.png">
