### ISSUE TITLE
Social media button are not redirecting

### ISSUE THREAD

**Issue by marianovegab** [seesawlabs/seesawlabs.github.io#89]
## Links for test
https://luigicr18.github.io/seesawlabs.github.io/

## Steps to Reproduce / Test
1- Go to https://luigicr18.github.io/seesawlabs.github.io/ on iPhone 6s 
2- Scroll down to the footer 
3- Click on "twitter" "facebook" or "linkedin" buttons 

**Expected Result**
The should redirect to  seesawlabs socials accounts

**Actual Result**
It is making the window scroll up to home

## Annotated Wireframes / Screenshots
<img width="742" alt="screen shot 2016-12-23 at 4 13 54 pm" src="https://cloud.githubusercontent.com/assets/8145017/21463258/21e6c716-c92c-11e6-9d4a-4b9d5f2733ae.png">

**Comment by luigicr18** [comment]
@mjbarnes88 need social media links

**Comment by mjbarnes88** [comment]
You can hide Facebook for now

https://twitter.com/seesawlabs

https://www.linkedin.com/company/seesaw-labs

**Comment by marianovegab** [comment]
Hello Guys
The twitter button is redirecting to Jeff's twitter account is this ok ? @mjbarnes88 
<img width="969" alt="screen shot 2016-12-26 at 1 43 30 pm" src="https://cloud.githubusercontent.com/assets/8145017/21485957/627ff9ae-cb71-11e6-8e89-4f9bf97f9a57.png">
Thanks

**Comment by mjbarnes88** [comment]
It's fine for now since no one practically ever clicks these things and they provide more fringe benefit than anything, but @jefftulsa we should have a larger discussion around "social presence" when I probably see you next week.
