### ISSUE TITLE
Change Favicon

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#93]
@luigicr18 it looks like the favicon is still the old one. You can switch it to the new one we used in the dev site.

Currently: 
![image](https://cloud.githubusercontent.com/assets/23315246/21507406/e93fd962-cc45-11e6-828b-f9e124be02a0.png)

Change to:
![image](https://cloud.githubusercontent.com/assets/23315246/21507417/09d16100-cc46-11e6-9146-1b5ec446f100.png)

**Comment by marianovegab** [comment]
Hello guys 
Working good on: https://luigicr18.github.io/seesawlabs.github.io/


<img width="303" alt="screen shot 2017-01-05 at 12 30 36 pm" src="https://cloud.githubusercontent.com/assets/8145017/21692509/d6d6dab0-d342-11e6-8c82-6f68367e3ced.png">


Thanks

**Comment by mjbarnes88** [comment]
This looks good, but the correct favicon was on the dev site already, so just make sure that it transfers over to the new site when you push changes @luigicr18
