### ISSUE TITLE
Adjust section header padding to match mock

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#97]
Current
![image](https://cloud.githubusercontent.com/assets/23315246/21507902/7855b2ee-cc4a-11e6-9834-7c642b851872.png)

Mock
![image](https://cloud.githubusercontent.com/assets/23315246/21507916/87321866-cc4a-11e6-823b-ffaa11f8ef5e.png)

Current
![image](https://cloud.githubusercontent.com/assets/23315246/21507942/ab775dbc-cc4a-11e6-92e8-1afecdf99d9c.png)

Mock
![image](https://cloud.githubusercontent.com/assets/23315246/21507950/bf4f91ba-cc4a-11e6-8783-13771310630f.png)

**Comment by marianovegab** [comment]
Hello
This is working good now

<img width="1563" alt="screenshot at jan 05 12-47-19" src="https://cloud.githubusercontent.com/assets/8145017/21693072/237e047c-d345-11e6-847a-6b1842b96e73.png">
<img width="1387" alt="screenshot at jan 05 12-47-01" src="https://cloud.githubusercontent.com/assets/8145017/21693073/237e37a8-d345-11e6-99c0-90e16b45bc38.png">

Thanks

**Comment by mjbarnes88** [comment]
For "Our process" section, we should set the max width by px instead of % to ensure that the text breaks at the end of the sentence instead of after the word strict.

This should work.

#ourProcess p {
    max-width: 850px;
}
