### ISSUE TITLE
Correct Font Family in Process Section

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#98]
Currently Helvetica

![image](https://cloud.githubusercontent.com/assets/23315246/21508031/732175f0-cc4b-11e6-944e-ab09be0f2b99.png)

Change to:
    font-family: openSansBold;

![image](https://cloud.githubusercontent.com/assets/23315246/21508030/7085f794-cc4b-11e6-9db3-8de3b8415729.png)

**Comment by marianovegab** [comment]
Looking good now

<img width="1111" alt="screenshot at jan 05 14-49-11" src="https://cloud.githubusercontent.com/assets/8145017/21697320/70e180f6-d357-11e6-8609-da9b63f82cd8.png">
