### ISSUE TITLE
Even out footer padding on Mobile and Tablet

### ISSUE THREAD

**Issue by mjbarnes88** [seesawlabs/seesawlabs.github.io#99]
On tablet everything is a bit squashed at the bottom, space things out a bit to make it look more like the desktop version.

Current: 
![image](https://cloud.githubusercontent.com/assets/23315246/21508230/55572e3c-cc4d-11e6-9f44-e35bb91eb068.png)

On Mobile it's spread out but there isn't enough padding at the top.
Current: 
![image](https://cloud.githubusercontent.com/assets/23315246/21508244/7fc2dbbc-cc4d-11e6-9d48-e78a84948839.png)

Mockup:
![image](https://cloud.githubusercontent.com/assets/23315246/21508251/8d868ae6-cc4d-11e6-8e42-0850f9927894.png)

**Comment by marianovegab** [comment]
Looking good on mobile:
![d5a9eb6f-5ce5-4c42-91fc-676152aea511](https://cloud.githubusercontent.com/assets/8145017/21697739/66dc974c-d359-11e6-9213-4995c774ba5c.jpg)

Tablet still need more space:
<img width="577" alt="screen shot 2017-01-05 at 3 13 04 pm" src="https://cloud.githubusercontent.com/assets/8145017/21697748/7ad0825e-d359-11e6-8eb0-b9e4abdec901.png">

**Comment by marianovegab** [comment]
Looking good on tablet:


<img width="500" alt="screen shot 2017-01-05 at 4 34 58 pm" src="https://cloud.githubusercontent.com/assets/8145017/21700216/f09a80ba-d364-11e6-8b61-b3fb91ca4af3.png">
